export interface PlayerMatchStat {
  playerId: string;
  minutesPlayed: number;
  goals: number;
  defenses: number;
  assists: number;
  goalMinutes?: number[];
  assistTargets?: string[];
  yellowCardMinute?: number;
  secondYellowCardMinute?: number;
  redCardMinute?: number;
  distanceKm: number;
  rating: number;
  yellowCard: boolean;
  secondYellowCard?: boolean;
  redCard: boolean;
  cleanSheet?: boolean;
  substituteIn?: string | undefined;
  totalPasses?: number;
  passPrecision?: number;
  passesMissed?: number;
  totalFinishings?: number;
  finishingPrecision?: number;
  finishingsMissed?: number;
  totalDribbles?: number;
  dribblePrecision?: number;
  dribblesMissed?: number;
  keyPasses?: number;
  ballsRecovered?: number;
  ballsLost?: number;
}
