import { Players } from "../../../../../../common/interfaces/playersInfo/players";

export type AggregatedPlayerStats = {
  player: Players;
  games: number;
  avgRating: number;
  goals: number;
  assists: number;
  goalParticipations: number;
  goalFrequency: number;
  assistFrequency: number;
  participationFrequency: number;
  totalFinishings: number;
  finishingsPerGame: number;
  finishingsOnTarget: number;
  finishingsOnTargetPerGame: number;
  finishingsMissed: number;
  finishingsMissedPerGame: number;
  totalPasses: number;
  passesPerGame: number;
  passesCompleted: number;
  passesCompletedPerGame: number;
  passesMissed: number;
  passesMissedPerGame: number;
  keyPasses: number;
  keyPassesPerGame: number;
  totalDribbles: number;
  dribblesPerGame: number;
  dribblesCompleted: number;
  dribblesCompletedPerGame: number;
  dribblesMissed: number;
  dribblesMissedPerGame: number;
  ballsRecovered: number;
  ballsRecoveredPerGame: number;
  ballsLost: number;
  ballsLostPerGame: number;
  yellowCards: number;
  yellowCardsPerGame: number;
  redCards: number;
  redCardsPerGame: number;
  distanceKm: number;
  distanceKmPerGame: number;
  maxDistanceKmInGame: number;
  minutesPlayed: number;
};
