import { SavedLineup } from "../../../../pages/Match/types/Lineup";
import { MatchResult } from "../MatchResult";
import { MatchStatus } from "../MatchStatus";
import { PlayerMatchStat } from "../PlayerMatchStat";

export type Match = {
  matchesId: string;
  date: string;
  league: string;
  homeTeam: string;
  awayTeam: string;
  homeScore?: number;
  awayScore?: number;
  homePenScore?: number;
  awayPenScore?: number;
  result: MatchResult;
  status: MatchStatus;
  playerStats?: PlayerMatchStat[];
  lineup?: SavedLineup;
  stoppage1T?: number;
  stoppage2T?: number;
  stoppageET1?: number;
  stoppageET2?: number;
  hasExtraTime?: boolean;
  homePossession?: number;
  awayPossession?: number;
  homeXG?: number;
  awayXG?: number;
  homeBallRecovery?: number;
  awayBallRecovery?: number;
  homeFinishings?: number;
  awayFinishings?: number;
  homeFinishingsOnTarget?: number;
  awayFinishingsOnTarget?: number;
  homePasses?: number;
  awayPasses?: number;
  homePassesCompleted?: number;
  awayPassesCompleted?: number;
  homeDefenses?: number;
  awayDefenses?: number;
  homeYellowCards?: number;
  awayYellowCards?: number;
  homeRedCards?: number;
  awayRedCards?: number;
};
