import { Players } from "../../../../../../common/interfaces/playersInfo/players";

export type AggregatedPlayerStats = {
  player: Players;
  games: number;
  avgRating: number;
  goals: number;
  assists: number;
  goalParticipations: number;
  goalFrequency: number;
  assistFrequency: number;
  participationFrequency: number;
  totalFinishings: number;
  finishingsOnTarget: number;
  finishingsMissed: number;
  totalPasses: number;
  passesCompleted: number;
  passesMissed: number;
  keyPasses: number;
  totalDribbles: number;
  dribblesCompleted: number;
  ballsRecovered: number;
  dribblesMissed: number;
  ballsLost: number;
  yellowCards: number;
  finishingsPer90: number;
  finishingsOnTargetPer90: number;
  finishingsMissedPer90: number;
  passesPer90: number;
  passesCompletedPer90: number;
  passesMissedPer90: number;
  keyPassesPer90: number;
  dribblesPer90: number;
  dribblesCompletedPer90: number;
  dribblesMissedPer90: number;
  ballsRecoveredPer90: number;
  ballsLostPer90: number;
  yellowCardsPer90: number;
  redCardsPer90: number;
  distanceKmPer90: number;
  redCards: number;
  distanceKm: number;
  maxDistanceKmInGame: number;
  minutesPlayed: number;
  minutesPerGame: number;
};
