export const createCuriositiesState = () => ({
  biggestWin: { diff: 0, text: "-" },
  worstLoss: { diff: 0, text: "-" },
  highestPossession: { val: 0, text: "-" },
  opponentStats: {} as Record<
    string,
    { wins: number; losses: number; games: number }
  >,
  scoreFrequency: {} as Record<string, number>,
  scoreFrequencyWhenScoring: {} as Record<string, number>,
  opponentMatchGoals: {} as Record<string, Set<string>>,

  currentUnbeaten: 0,
  maxUnbeaten: 0,
  currentWinless: 0,
  maxWinless: 0,
  currentHomeUnbeaten: 0,
  maxHomeUnbeaten: 0,
  currentAwayUnbeaten: 0,
  maxAwayUnbeaten: 0,
  currentWinStreak: 0,
  maxWinStreak: 0,
  currentScoringStreak: 0,
  maxScoringStreak: 0,
  currentCleanSheetStreak: 0,
  maxCleanSheetStreak: 0,
  currentConcedingStreak: 0,
  maxConcedingStreak: 0,

  fastestGoal: { min: 999, player: "", text: "-" },
  latestGoal: { min: 0, player: "", text: "-" },
  latestWinGoal: { min: 0, text: "-" },
  latestDrawGoal: { min: 0, text: "-" },

  goalsFirstHalf: 0,
  goalsSecondHalf: 0,
  craziestMatch: { goals: 0, text: "-" },

  unbeatenWhenScoringFirstCount: 0,
  scoredFirstGamesCount: 0,
  comebackWinsCount: 0,
  precisionMatchesCount: 0,
  explosiveMatchesCount: 0,
  blankMatchesCount: 0,
  overwhelmingStartsCount: 0,
  dramaticEndsCount: 0,

  biggestComebackWin: { deficit: 0, text: "-" },
  biggestComebackLoss: { lead: 0, text: "-" },

  opponentGoalsScored: {} as Record<string, number>,
  drawsByOpponent: {} as Record<string, number>,
  opponentTeamsScorers: {} as Record<string, number>,
  punchingBagDiffs: {} as Record<string, number>,
  teamGoalsMinute: {} as Record<number, number>,
  concededGoalsMinute: {} as Record<number, number>,
  opponentScorers: {} as Record<string, number>,
  teamDuos: {} as Record<string, number>,
  opponentDuos: {} as Record<string, number>,
  playerGoalMinutes: {} as Record<string, number>,
  playerAssistMinutes: {} as Record<string, number>,
  decisivePlayers: {} as Record<string, number>,
  openerPlayers: {} as Record<string, number>,
  winAssistants: {} as Record<string, number>,
  stoppageTimeExperts: {} as Record<string, number>,
  dangerousIntervals: {} as Record<string, number>,
  opponentGoalParticipations: {} as Record<string, number>,
});

export type CuriositiesState = ReturnType<typeof createCuriositiesState>;
