import { PlayerFormTexts } from "../../../forms/types/PlayerFormTexts";

export const TEXTS: PlayerFormTexts = {
  nameLabel: "Nome do Jogador",
  namePlaceholder: "Ex: João Silva",
  nationalityLabel: "Nacionalidade",
  nationalityPlaceholder: "Ex: BRA",
  ageLabel: "Idade",
  agePlaceholder: "16",
  sectorLabel: "Setor",
  sectorPlaceholder: "Selecione o setor",
  positionLabel: "Posição",
  positionPlaceholder: "Selecione a posição",
  overallLabel: "Overall (OVR)",
  overallPlaceholder: "60",
  potentialLabel: "Potencial",
  potentialPlaceholder: "Ex: 80-90",
  heightLabel: "Altura (cm)",
  heightPlaceholder: "180",
  weightLabel: "Peso (kg)",
  weightPlaceholder: "75",
  shirtNumberLabel: "Número da Camisa",
  shirtNumberPlaceholder: "Ex: 10",
  annotationsLabel: "Anotações do Olheiro",
  annotationsPlaceholder: "Observações...",
  arrivalDateLabel: "Data de Chegada",
  arrivalDatePlaceholder: "DD/MM",
  submitText: "Adicionar Jogador",
  loadingText: "Salvando...",
  evolutionDateLabel: "Data da Evolução",
  evolutionDatePlaceholder: "DD/MM",
};
