export enum ModalType {
  NONE = "",
  NEW_CAREER = "NEW_CAREER",
  DELETE_CONFIRM = "DELETE_CONFIRM",
  ADD_CLUB_IMG = "ADD_CLUB_IMG",
  EDIT_CLUB = "EDIT_CLUB",
  SLIDE_UP_PANEL = "SLIDE_UP_PANEL",
  DELETE_PLAYER_CONFIRM = "DELETE_PLAYER_CONFIRM",
  SELL_PLAYER = "SELL_PLAYER",
}
