import {
  IoBookOutline,
  IoTrophyOutline,
  IoCalendarOutline,
  IoPeopleOutline,
  IoFootballOutline,
  IoListOutline,
  IoStatsChartOutline,
  IoStarOutline,
  IoBusinessOutline,
  IoSchoolOutline,
  IoBulbOutline,
  IoPersonOutline,
  IoPlayOutline,
  IoDiamondOutline,
  IoTimeOutline,
  IoAnalyticsOutline,
  IoLibraryOutline,
  IoOptionsOutline,
} from "react-icons/io5";
import Styles from "../../Tutorial.module.css";

export const sectionIcons = [
  <IoBookOutline className={Styles.icon} />,
  <IoTrophyOutline className={Styles.icon} />,
  <IoCalendarOutline className={Styles.icon} />,
  <IoPeopleOutline className={Styles.icon} />,
  <IoFootballOutline className={Styles.icon} />,
  <IoListOutline className={Styles.icon} />,
  <IoStatsChartOutline className={Styles.icon} />,
  <IoStarOutline className={Styles.icon} />,
  <IoBusinessOutline className={Styles.icon} />,
  <IoSchoolOutline className={Styles.icon} />,
  <IoBulbOutline className={Styles.icon} />,
  <IoPersonOutline className={Styles.icon} />,
  <IoPlayOutline className={Styles.icon} />,
  <IoDiamondOutline className={Styles.icon} />,
  <IoTimeOutline className={Styles.icon} />,
  <IoAnalyticsOutline className={Styles.icon} />,
  <IoLibraryOutline className={Styles.icon} />,
  <IoOptionsOutline className={Styles.icon} />,
];
